"""add image_data to bin_types

Revision ID: 1d273e51591b
Revises: bea9d362cb90
Create Date: 2026-03-05 13:19:01.117298

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d273e51591b'
down_revision: Union[str, None] = 'bea9d362cb90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bin_types', sa.Column('image_data', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bin_types', 'image_data')
    # ### end Alembic commands ###
