"""add labelled column to bins

Revision ID: cbaff9fe9797
Revises: 2f9529c4514d
Create Date: 2026-03-05 16:35:54.535094

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbaff9fe9797'
down_revision: Union[str, None] = '2f9529c4514d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bins', sa.Column('labelled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bins', 'labelled')
    # ### end Alembic commands ###
