"""replace level with bottom_id

Revision ID: 4746e6ec3de6
Revises: 0f3e965df26a
Create Date: 2026-03-05 12:43:14.012584

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4746e6ec3de6'
down_revision: Union[str, None] = '0f3e965df26a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bins', sa.Column('bottom_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bins', 'bins', ['bottom_id'], ['id'])
    op.drop_column('bins', 'level')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bins', sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'bins', type_='foreignkey')
    op.drop_column('bins', 'bottom_id')
    # ### end Alembic commands ###
