"""add grid dims to rooms and bin_type_id orientation to stacks

Revision ID: 096cb67830f3
Revises: 1d273e51591b
Create Date: 2026-03-05 13:45:16.072676

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '096cb67830f3'
down_revision: Union[str, None] = '1d273e51591b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('grid_rows', sa.Integer(), nullable=True))
    op.add_column('rooms', sa.Column('grid_cols', sa.Integer(), nullable=True))
    op.add_column('stacks', sa.Column('bin_type_id', sa.Integer(), nullable=True))
    op.add_column('stacks', sa.Column('orientation', sa.String(), nullable=True))
    op.create_foreign_key(None, 'stacks', 'bin_types', ['bin_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stacks', type_='foreignkey')
    op.drop_column('stacks', 'orientation')
    op.drop_column('stacks', 'bin_type_id')
    op.drop_column('rooms', 'grid_cols')
    op.drop_column('rooms', 'grid_rows')
    # ### end Alembic commands ###
