"""add align_h align_v to stacks

Revision ID: 3a69e7a9b891
Revises: 096cb67830f3
Create Date: 2026-03-05 13:52:51.427700

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a69e7a9b891'
down_revision: Union[str, None] = '096cb67830f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stacks', sa.Column('align_h', sa.String(), nullable=True))
    op.add_column('stacks', sa.Column('align_v', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stacks', 'align_v')
    op.drop_column('stacks', 'align_h')
    # ### end Alembic commands ###
