"""add bin_types table and bin_type_id

Revision ID: bea9d362cb90
Revises: 4746e6ec3de6
Create Date: 2026-03-05 13:10:03.222393

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bea9d362cb90'
down_revision: Union[str, None] = '4746e6ec3de6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bin_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('width_mm', sa.Float(), nullable=False),
    sa.Column('depth_mm', sa.Float(), nullable=False),
    sa.Column('height_mm', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_bin_types_id'), 'bin_types', ['id'], unique=False)
    op.add_column('bins', sa.Column('bin_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bins', 'bin_types', ['bin_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bins', type_='foreignkey')
    op.drop_column('bins', 'bin_type_id')
    op.drop_index(op.f('ix_bin_types_id'), table_name='bin_types')
    op.drop_table('bin_types')
    # ### end Alembic commands ###
