"""move orientation offset to bins remove from stacks

Revision ID: 49bab30078ca
Revises: 3a69e7a9b891
Create Date: 2026-03-05 13:59:48.642370

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49bab30078ca'
down_revision: Union[str, None] = '3a69e7a9b891'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bins', sa.Column('orientation', sa.String(), nullable=True))
    op.add_column('bins', sa.Column('offset_x', sa.Float(), nullable=True))
    op.add_column('bins', sa.Column('offset_y', sa.Float(), nullable=True))
    op.drop_constraint('stacks_bin_type_id_fkey', 'stacks', type_='foreignkey')
    op.drop_column('stacks', 'align_v')
    op.drop_column('stacks', 'bin_type_id')
    op.drop_column('stacks', 'align_h')
    op.drop_column('stacks', 'orientation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stacks', sa.Column('orientation', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('stacks', sa.Column('align_h', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('stacks', sa.Column('bin_type_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('stacks', sa.Column('align_v', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('stacks_bin_type_id_fkey', 'stacks', 'bin_types', ['bin_type_id'], ['id'])
    op.drop_column('bins', 'offset_y')
    op.drop_column('bins', 'offset_x')
    op.drop_column('bins', 'orientation')
    # ### end Alembic commands ###
