apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: storage-organizer
  labels:
    app: backend
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30800
    protocol: TCP
    name: http
  selector:
    app: backend
