apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: storage-organizer
  namespace: storage-organizer
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - host: organizer.bryanbickford.com
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 8000
      - path: /docs
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 8000
      - path: /openapi.json
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 8000
      - path: /health
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 8000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 3000
