apiVersion: v1
kind: PersistentVolume
metadata:
  name: uploads-pv
  labels:
    type: local
    app: backend
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/lib/storage_organizer/uploads
    type: DirectoryOrCreate
